server:
  port: 5555

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defalutZone: http://localhost:8761/eureka

spring:
    application:
        name: apigateway-service
    cloud:
        gateway:
            routes:
                - id: trip-service
                  uri: lb://TRIP-SERVICE
                  predicates:
                    - Path=/trips/**, /user/**
                