server:
  port: 5555

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defalutZone: http://localhost:8761/eureka

spring:
    application:
        name: apigateway-service
    cloud:
        gateway:
            routes:
                - id: trip-service
                  uri: lb://TRIP-SERVICE
                  predicates:
                    - Path=/trips/**, /user/**
                  filters: 
                    - CustomAuthGatewayFilter
                
jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400                 